name: CI

on:
    push:
        branches:
            - main
            - next
    pull_request:
        branches:
            - main
            - next

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install Foundry
              uses: onbjerg/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Print forge version
              run: forge --version

            - name: Install dependencies
              run: npm ci

            - name: Cache artifacts
              uses: actions/cache@v3
              with:
                  key: "cache-artifacts-${{ runner.os }}-${{ hashFiles('contracts/**/*.sol', 'test/**/*.sol') }}"
                  path: |
                      ${{ github.workspace }}/artifacts
                      ${{ github.workspace }}/cache
                      ${{ github.workspace }}/forge-cache
                      ${{ github.workspace }}/foundry-out
                      ${{ github.workspace }}/typechain-types
                  restore-keys: |
                      cache-artifacts-${{ runner.os }}-

            - name: Compile contracts
              run: npm run build

            - name: Run linter
              run: npm run lint

            - name: Run forge test
              run: npm run forge:test
